slang = en,eng,ja,jap,unknown
demuxer-mkv-subtitle-preroll=yes

sub-font='Liberation Sans'
sub-font-size=45  
sub-bold=no
sub-border-color='#FF0F0F0F'  
sub-border-size=4.0            
sub-shadow-color='#FF0F0F0F'  
sub-shadow-offset=5.0          

sub-margin-x=20                
sub-margin-y=20                

sub-fix-timing=yes
sub-auto=fuzzy                 # all || exact || fuzzy  
sub-file-paths-append=subs
