slang = en,eng,ja,jap,unknown
demuxer-mkv-subtitle-preroll=yes
sub-font='Liberation Sans'                                                
sub-font-size=45                      
sub-bold=no
sub-border-color="#FF000000"
sub-border-size=3.0
sub-shadow-color="#FF000000"
sub-shadow-offset=5.0
sub-margin-x=25
sub-margin-y=30                 # 22 default                            
sub-fix-timing=yes                     
sub-auto=fuzzy                  # all || exact || fuzzy                         
sub-file-paths-append=subs 
 