R cycle_values video-rotate 90 180 270 0
d cycle deband
a cycle audio
s cycle sub
h cycle-values hwdec d3d11va-copy no             # didn't used d3d11va because video-rotate cpu can't do, if complete process is happening on iGPU .
ctrl+f cycle sub-bold;cycle-values sub-border-size '2.4' '4.0'; cycle-values sub-shadow-offset '0.75' '5' ; cycle-values sub-font 'Gandhi Sans' 'Liberation Sans'; 
S async screenshot
