# Volume
# ======
WHEEL_UP add volume 5
WHEEL_DOWN add volume -5
UP add volume 5
DOWN add volume -5

# Chapter
# =======
# MOUSE_BTN0 add chapter -1  # mine left click is 0
# MOUSE_BTN2 add chapter 1    # mine right click is 2
# MOUSE_BTN1 show-progress  # mine middle button is 1

# Subtitle Track Change
# =====================
s cycle sub

# Audio Track Change
# ==================
a cycle audio

# Audio Downmix Toggle
# ====================
+ cycle-values audio-channels stereo auto-safe

# Screenshot
# ====================
S async screenshot

# Video Debanding Toggle
# ======================
d cycle deband

R cycle_values video-rotate 90 180 270 0
ctrl+m cycle window-minimized
SHIFT+m cycle window-maximized