input-ipc-server=\\.\pipe\mpvsocket

ontop=yes 
border=no                                     # disable windows title bar
blend-subtitles=yes                           # if value is set to "video" then if anime/movie is blurry then subtitles also will be blurry
force-seekable=yes
keep-open=yes                                 # 'always' -> will keep open at each episode end in the folder.
                                              # 'yes'    -> will keep open only at the last episode of the season in the folder.
use-filedir-conf                              # enables directory-specific configuration first mpv.conf(main) is loaded then this
no-hidpi-window-scale
vf=sub                                        # sub also rotates with rotated video

#video-unscaled=no|yes|downscale-big          # yes for lower resolution than the monitor(but when mpv window is made very small, video will be cropped), to solve it use Downscale-big.

ignore-path-in-watch-later-config
watch-later-options-remove=fullscreen
watch-later-options-remove=volume
watch-later-directory=".\\watch-later"        
write-filename-in-watch-later-config          

#save-position-on-quit


include="~~/configs/mpv_audio.conf"
include="~~/configs/mpv_deband.conf"
include="~~/configs/mpv_osd.conf"
include="~~/configs/mpv_performance.conf"
include="~~/configs/mpv_profile.conf"
include="~~/configs/mpv_screenshot.conf"
include="~~/configs/mpv_sub.conf"