audio-samplerate=48000
audio-channels=2
alang=ko,kor,korean,ja,jp,jpn,japanese,en,eng,english,hi,hin,hindi,unknown
volume-max=200                
volume=100
audio-channels=auto-safe     
audio-pitch-correction=yes