vo=gpu                       # Vaapi crashes my VivoBook X415EA ;(
hwdec=no                     # "no" is required for vf=sub to work


 ytdl-raw-options=format=best[height<=360],sub-langs="en,en-US,en-IN,en-GB",write-auto-sub= # for youtube movies (360p)
 #cache=yes                    # default: auto || "yes" will lead to more RAM usage and yes is automatic selected for youtube links
 cache-secs=1200               # 20 m  || default: 1000 hours bro wtf
 demuxer-max-bytes=75M         # 75MB   || default: 150MB

 #cache-on-disk=yes 
 #demuxer-cache-dir=.\

# "Cache-on-disk" will store viewed (past scenes) in cached parts when enabled. Otherwise, it is deleted after viewing.
# If 1GB cache is insufficient for 20 minutes, then it will load whatever it can in that 1GB (e.g., 15-18 minutes)

# These are Default/integrated GPU Laptop settings #
scale=lanczos     #  General video Upscaling, adjusting the video's resolution and size.
dscale=hermite    #  General video Downscaling

dither-depth=8
