vo=gpu                                                # Vaapi crashes my VivoBook X415EA ;(
gpu-api=d3d11                                         # for Intel integrated GPUs
hwdec=d3d11va-copy                                    # "no" is required for vf=sub to work
scale=bilinear                                        # General video upscaling filter
cscale=bilinear                                       # Chroma (color) upscaling filter
dscale=mitchell                                       # Video downscaling filter
dither-depth=8
#glsl-shaders="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl"   # a neural network-based upscaler. It boosts the resolution of your video by 2x