jump_buttons=yes
chapter_skip_buttons=yes
track_nextprev_buttons=yes
volume_control=yes
playlist_button=yes
hide_empty_playlist_button=yes
gray_empty_playlist_button=yes
download_button=no
download_path=~~downloads
screenshot_button=yes
ontop_button=no
speed_button=yes
info_button=yes
fullscreen_button=yes

seekbarfg_color=#42C9E3
seekbarbg_color=#FFFFFF
seekbar_cache_color=#42C9E3

persistentprogress=yes
persistentprogressheight=17